# Default values for transaction-service-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: inferno681/transaction_service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    memory: "500Mi"
    cpu: "200m"
  requests:
    memory: "350Mi"
    cpu: "100m"

readinessProbe:
  httpGet:
    path: /api/healthz/ready
    port: 8000
  failureThreshold: 10
  initialDelaySeconds: 3
  periodSeconds: 2

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: transaction-service-config-volume
    mountPath: /app/src/config/config.yaml
    subPath: config.yaml

nodeSelector: {}

tolerations: []

affinity: {}

app:
  servicePort: 8000
  data:
    config.yaml: |
      service:
        title: "Transaction service"
        description: "Сервис транзакций"
        host: "0.0.0.0"
        port: 8000
        debug: True
        db_hostname: "postgres-service"
        db_port: 5432
        db_name: vstakrotskij
        db_username: username
        db_echo: False
        tags_metadata_transaction:
          name: "Transaction"
          description: "Управление транзакциями"
        tags_metadata_health:
          name: "Health"
          description: "Проверка доступности сервиса"
      jaeger:
        service_name: "transaction_service"
        host: "jaeger-query-service"
        port: 6831
        logging: True
        sampler_type: "const"
        sampler_param: 1
  secret_data:
    db_password: cGFzc3dvcmQ=
