FROM python:3.12-slim

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
    libgl1-mesa-glx \
    libglib2.0-dev

WORKDIR /app

RUN pip install --no-cache-dir poetry

COPY pyproject.toml poetry.lock* /app/

RUN poetry config virtualenvs.create false

RUN poetry install

COPY ./alembic.ini  ./alembic.ini

COPY ./setup.cfg  ./setup.cfg

COPY ./src  ./src

ENV PYTHONPATH=/app/src/

CMD ["sh", "-c", "while true; do sleep 1; done"]
