service:
  title: "Transaction service"
  description: "Сервис транзакций"
  host: "0.0.0.0"
  port: 8000
  debug: True
  tags_metadata:
    name: "Transaction"
    description: "Управление транзакциями"
