service:
  title: "Transaction service"
  description: "Сервис транзакций"
  host: "0.0.0.0"
  port: 8000
  debug: True
  tags_metadata_transaction:
    name: "Transaction"
    description: "Управление транзакциями"
  tags_metadata_health:
    name: "Health"
    description: "Проверка доступности сервиса"
