service:
  title: "Transaction service"
  description: "Transaction service"
  host: "0.0.0.0"
  port: 8000
  debug: True
  db_hostname: "db"
  db_port: 5432
  db_name: postgres
  db_username: postgres
  db_echo: False
  tags_metadata_transaction:
    name: "Transaction"
    description: "Transaction creation"
  tags_metadata_health:
    name: "Health"
    description: "Health check"

jaeger:
  service_name: "transaction_service"
  host: "jaeger"
  port: 6831
  logging: True
  sampler_type: "const"
  sampler_param: 1

redis:
  url: "redis://redis:6379"
  db: 1
  decode_responses: True
