apiVersion: v1
kind: ConfigMap
metadata:
  name: stakrotckii-transaction-service-configmap
data:
  config.yaml: |
    service:
      title: "Transaction service"
      description: "Сервис транзакций"
      host: "0.0.0.0"
      port: 8000
      debug: True
      db_hostname: "postgres-service"
      db_port: 5432
      db_name: vstakrotskij
      db_username: username
      db_echo: False
      tags_metadata_transaction:
        name: "Transaction"
        description: "Управление транзакциями"
      tags_metadata_health:
        name: "Health"
        description: "Проверка доступности сервиса"

    jaeger:
      service_name: "transaction_service"
      host: "jaeger-query-service"
      port: 6831
      logging: True
      sampler_type: "const"
      sampler_param: 1
