apiVersion: v1
kind: Service
metadata:
  name: stakrotckii-transaction-service-service
spec:
  selector:
    app.kubernetes.io/name: stakrotckii
    app.kubernetes.io/instance: transaction-service-abcxyz
  ports:
    - port: 8000
      targetPort: 8000
