"""initial

Revision ID: b9b276be0e05
Revises:
Create Date: 2024-08-18 04:05:15.485176

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9b276be0e05'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('debit', 'credit', name='transactiontype').create(op.get_bind())
    op.create_table(
        'report',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('user_id', sa.INTEGER(), nullable=False),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('end_date', sa.DateTime(), nullable=False),
        sa.Column('debit', sa.Integer(), nullable=False),
        sa.Column('credit', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'transaction',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('user_id', sa.INTEGER(), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column(
            'transaction_type',
            postgresql.ENUM(
                'debit',
                'credit',
                name='transactiontype',
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('TIMEZONE("utc", now())'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'report_transaction',
        sa.Column('report_id', sa.Integer(), nullable=False),
        sa.Column('transaction_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['report_id'],
            ['report.id'],
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['transaction_id'],
            ['transaction.id'],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('report_id', 'transaction_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_transaction')
    op.drop_table('transaction')
    op.drop_table('report')
    sa.Enum('debit', 'credit', name='transactiontype').drop(op.get_bind())
    # ### end Alembic commands ###
