name: main

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker
        options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose-test.yaml up -d --build
      - name: Run Pytest
        run: |
          docker compose -f docker-compose-test.yaml exec transaction_service pytest --cov --cov-fail-under=90 --cov-report term-missing --cov-report xml:coverage.xml
          docker cp $(docker compose -f docker-compose-test.yaml ps -q transaction_service):/app/coverage.xml ./coverage.xml
      - name: Tear down Docker Compose
        if: always()
        run: docker compose -f docker-compose-test.yaml down
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build_and_push_to_docker_hub:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.CONTAINER_NAME }}:latest

  send_message:
    name: Send message
    runs-on: ubuntu-latest
    needs:
      - test
      - build_and_push_to_docker_hub
    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.actor }} merge pull request with commit ${{ github.event.commits[0].message }}!
          Link to commit - https://github.com/${{ github.repository }}/commit/${{github.sha}}
