name: pre-commit

on:
 pull_request:
  types: [opened, synchronize, reopened]

jobs:
 linters:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Linter and mypy
      run:  |
        poetry run flake8 src/
        poetry run mypy src/

 tests:
  runs-on: ubuntu-latest
  services:
    docker:
      image: docker
      options: --privileged
  steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Compose
      run: |
        docker compose -f docker-compose-test.yaml up -d --build
    - name: Run Pytest
      run: docker compose -f docker-compose-test.yaml exec transaction_service pytest --cov --cov-fail-under=90 --cov-report term-missing
    - name: Tear down Docker Compose
      run: docker compose -f docker-compose-test.yaml down
